web_app/smartprobe_web/__init__.py
import decimal
import json
import os

from flask import Flask

class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return float(o)
        return json.JSONEncoder.default(self, o)

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
    )
    app.json_encoder = DecimalEncoder

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import views
    app.register_blueprint(views.bp)

    from . import api
    app.register_blueprint(api.bp)

    return app

web_app/smartprobe_web/views.py
import functools

from flask import Blueprint, render_template, redirect, url_for

bp = Blueprint("views", __name__)

@bp.route("/")
def index():
    return redirect(url_for("views.overview"))

@bp.route("/node/")
def overview():
    return render_template("overview.html")

@bp.route("/node/<node_id>")
def node(node_id):
    return render_template("node.html", node_id=node_id)

web_app/smartprobe_web/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title></title>

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.css"/>

    <link href="{{ url_for("static", filename="/css/styles.css") }}" rel="stylesheet">

    <!--Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css" integrity="sha384-7ynz3n3tAGNUYFZD3cWe5PDcE36xj85vyFkawcF6tIwxvIecqKvfwLiaFdizhPpN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous">
  </head>

  <body>
    <header class="d-flex justify-content-center py-3 border-bottom mb-5 shadow-sm">
      <a href="{{ url_for("views.index") }}" class="d-flex align-items-center text-dark text-decoration-none fs-2">
        <i class="bi bi-layers-half"></i>
        <span class="ms-2">SmartProbe</span>
      </a>
    </header>

    <main class="container">
      {% block main %}{% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.js"></script>
    <script src="{{ url_for("static", filename="/js/helper.js") }}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

web_app/smartprobe_web/templates/node.html
{% extends 'base.html' %}

{% block main %}
<nav style="--bs-breadcrumb-divider: '>';">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Nodes</a></li>
    <li class="breadcrumb-item active"><a>{{ node_id }}</a></li>
  </ol>
</nav>
<div class="row g-3">
  <section class="col-12 col-lg-4">
    <div class="row g-0 border rounded shadow-sm">
      <div class="col-6 col-lg-12">
        <img id="node-img" class="w-100" src="http://cohenwoodworking.com/wp-content/uploads/2016/09/image-placeholder-500x500.jpg">
      </div>
      <div class="col">
        <div id="btns" class="row g-0 h-100">
          <a style="color: black;" id="btn-temperature" class="col-6 col-lg-3 d-flex flex-column justify-content-center py-lg-3 py-xl-4 text-decoration-none" role="button">
            <i class="bi bi-thermometer-half text-center"></i>
            <span class="text-center">
              <span id="node-temperature">0</span>&#8451;
            </span>
          </a>
          <a style="color: black;" id="btn-moisture" class="col-6 col-lg-3 d-flex flex-column justify-content-center py-lg-3 py-xl-4 text-decoration-none" role="button">
            <i class="bi bi-droplet text-center"></i>
            <span class="text-center">
              <span id="node-moisture">0</span>
            </span>
          </a>
          <a style="color: black;" id="btn-sprayer" class="col-6 col-lg-3 d-flex flex-column justify-content-center py-lg-3 py-xl-4 text-decoration-none" role="button">
            <i id="node-sprayer" class="bi bi-broadcast-pin text-center"></i>
            <span class="text-center">Sprayer</span>
          </a>
          <a style="color: black;" id="btn-sprinkler" class="col-6 col-lg-3 d-flex flex-column justify-content-center py-lg-3 py-xl-4 text-decoration-none" role="button">
            <i id="node-sprinkler" class="bi bi-water text-center"></i>
            <span class="text-center">Sprinkler</span>
          </a>
        </div>
      </div>
    </div>
  </section>
  <section class="col-12 col-lg-8">
    <div id="charts" class="h-100 border rounded shadow-sm p-3">
      <canvas id="chart-temperature"></canvas>
      <canvas id="chart-moisture" class="d-none"></canvas>
      <canvas id="chart-sprayer" class="d-none"></canvas>
      <canvas id="chart-sprinkler" class="d-none"></canvas>
    </div>
  </section>
  <section class="col-12">
    <div id="tables" class="border rounded shadow-sm p-3">
      <table id="table-temperature" class="table table-striped">
        <thead>
          <tr>
            <th>Timestamp</th>
            <th>Temperature</th>
          </tr>
        </thead>
      </table>
      <table id="table-moisture" class="table table-striped">
        <thead>
          <tr>
            <th>Timestamp</th>
            <th>Moisture</th>
          </tr>
        </thead>
      </table>
      <table id="table-sprayer" class="table table-striped">
        <thead>
          <tr>
            <th>Timestamp</th>
            <th>Sprayer</th>
          </tr>
        </thead>
      </table>
      <table id="table-sprinkler" class="table table-striped">
        <thead>
          <tr>
            <th>Timestamp</th>
            <th>Sprinkler</th>
          </tr>
        </thead>
      </table>
    </div>
  </section>
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luxon@^2"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@^1"></script>
<script src="{{url_for("static", filename="/js/services.js")}}"></script>
<script>
  function buildDataChart(ctx, key, title = "Title") {
    return new Chart(
      ctx,
      {
        type: "line",
        data: {
          datasets: [
            {
              label: title,
              backgroundColor: "rgb(255, 99, 132)",
              borderColor: "rgb(255, 99, 132)",
              parsing: {
                yAxisKey: key
              }
            },
            {
              label: "Action",
              backgroundColor: "rgb(132, 99, 255)",
              borderColor: "rgb(132, 99, 255)",
              parsing: {
                yAxisKey: "sprinkler"
              },
              stepped: true,
              yAxisID: "y2"
            }
          ]
        },
        options: {
          maintainAspectRatio: false,
          parsing: {
            xAxisKey: "timestamp",
          },
          scales: {
            x: {
              type: "time"
            },
            y: {
              type: "linear",
              position: "left",
              stack: "demo",
              stackWeight: 2,
            },
            y2: {
              type: "category",
              labels: ["W1", "W0"],
              offset: true,
              position: "left",
              stack: "demo",
              stackWeight: 1
            }
          }
        }
      }
    );
  }

  function buildActionsChart(ctx, key, labels, title = "Title") {
    return new Chart(
      ctx,
      {
        type: "line",
        data: {
          datasets: [
            {
              label: "Action",
              backgroundColor: "rgb(132, 99, 255)",
              borderColor: "rgb(132, 99, 255)",
              stepped: true
            }
          ]
        },
        options: {
          maintainAspectRatio: false,
          parsing: {
            xAxisKey: "timestamp",
            yAxisKey: key
          },
          scales: {
            x: {
              type: "time"
            },
            y: {
              type: "category",
              labels: labels,
              offset: true,
              position: "left",
            }
          }
        }
      }
    );
  }

  function buildTable(ctx, col) {
    return ctx.DataTable({
      searching: false,
      order: [[ 0, "desc" ]],
      columns: [
        { data: "timestamp" },
        { data: col },
      ]
    });
  }

  $(document).ready(function() {
    const service = new ServiceNode();
    const nodeId = "{{ node_id }}";

    const chartTemperature = buildDataChart($("#chart-temperature"), "temperature", "Temperature");
    const chartMoisture = buildDataChart($("#chart-moisture"), "moisture", "Moisture");
    const chartSprayer = buildActionsChart($("#chart-sprayer"), "sprayer", ["P1", "P0"], "Temperature");
    const chartSprinkler = buildActionsChart($("#chart-sprinkler"), "sprinkler", ["W1", "W0"], "Moisture");

    const tableTemperature = buildTable($("#table-temperature"), "temperature");
    const tableMoisture = buildTable($("#table-moisture"), "moisture");
    const tableSprayer = buildTable($("#table-sprayer"), "sprayer");
    const tableSprinkler = buildTable($("#table-sprinkler"), "sprinkler");

    $("#tables").children().each(function(index) {
      $(this).addClass("d-none");
    });
    $("#charts").children().each(function(index) {
      $(this).addClass("d-none");
    });
    
    setIntervalExec(function() {
      service.getNodeAsync(nodeId, function(node) {
        $("#node-temperature").text(node["sensors"]["temperature"]);
        $("#node-moisture").text(node["sensors"]["moisture"]);

        if (node["actions"]["sprayer"] == "P1") {
          $("#btn-sprayer").addClass("text-success");
        } else {
          $("#btn-sprayer").removeClass("text-success");
        }

        if (node["actions"]["sprinkler"] == "W1") {
          $("#btn-sprinkler").addClass("text-success");
        } else {
          $("#btn-sprinkler").removeClass("text-success");
        }
      });

      service.getNodeDataAsync(nodeId, function(log) {
        dataTemperature = [];
        dataMoisture = [];

        log.forEach(function(entry) {
          dataTemperature.push({
            timestamp: entry["timestamp"],
            temperature: entry["data"]["temperature"]
          });
          dataMoisture.push({
            timestamp: entry["timestamp"],
            moisture: entry["data"]["moisture"]
          });
        });

        chartTemperature.data.datasets[0].data = dataTemperature.slice(0, 51);
        chartTemperature.update();

        chartMoisture.data.datasets[0].data = dataMoisture.slice(0, 51);
        chartMoisture.update();

        tableTemperature
          .clear()
          .rows.add(dataTemperature)
          .draw();
        tableMoisture
          .clear()
          .rows.add(dataMoisture)
          .draw();
      });

      service.getNodeActionsAsync(nodeId, function(log) {
        actionsSprayer = [];
        actionsSprinkler = [];

        log.forEach(function(entry) {
          actionsSprayer.push({
            timestamp: entry["timestamp"],
            sprayer: entry["data"]["sprayer"]
          });
          actionsSprinkler.push({
            timestamp: entry["timestamp"],
            sprinkler: entry["data"]["sprinkler"]
          });
        });

        chartTemperature.data.datasets[1].data = actionsSprinkler.slice(0, 51);
        chartTemperature.update();

        chartMoisture.data.datasets[1].data = actionsSprinkler.slice(0, 51);
        chartMoisture.update();

        chartSprayer.data.datasets[0].data = actionsSprayer.slice(0, 51);
        chartSprayer.update();

        chartSprinkler.data.datasets[0].data = actionsSprinkler.slice(0, 51);
        chartSprinkler.update();

        tableSprayer
          .clear()
          .rows.add(actionsSprayer)
          .draw();
        tableSprinkler
          .clear()
          .rows.add(actionsSprinkler)
          .draw();
      });

      refreshImage(
        $("#node-img"),
        S3_ENDPOINT + `${nodeId}.bmp`
      )
    }, 5000);

    $("#btns").children().click(function() {
      let attribute = $(this).attr("id").split("-")[1];

      $("#btns").children().each(function(index) {
        $(this).removeClass("shadow");
      });
      $(this).addClass("shadow");

      $("#charts").children().each(function(index) {
        $(this).addClass("d-none");

        if ($(this).attr("id").includes(attribute)) {
          $(this).removeClass("d-none");
        }
      });

      $("#tables").children().each(function(index) {
        $(this).addClass("d-none");

        if ($(this).attr("id").includes(attribute)) {
          $(this).removeClass("d-none");
        }
      });
    });
  });
</script>
{% endblock %}

web_app/smartprobe_web/templates/overview.html
{% extends 'base.html' %}

{% block main %}
<div id="nodes" class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3">
</div>

<template id="template-node">
  <div class="col">
    <div class="card shadow-sm">
      <img name="node-img" class="card-img-top" src="http://cohenwoodworking.com/wp-content/uploads/2016/09/image-placeholder-500x500.jpg">
      <div class="card-body">
        <h5 class="card-title mb-0"><a name="node-id" class="link-dark"></a></h5>
      </div>
      <ul class="list-group list-group-flush flex-row">
        <li class="list-group-item border-0 w-100 d-flex flex-column">
          <i class="bi bi-thermometer-half text-center fs-4"></i>
          <span class="text-center">
            <span name="node-temperature"></span>&#8451;
          </span>
        </li>
        <li class="list-group-item border-0 border-end w-100 d-flex flex-column">
          <i class="bi bi-droplet text-center fs-4"></i>
          <span class="text-center">
            <span name="node-moisture"></span>
          </span>
        </li>
        <li class="list-group-item border-0 d-flex flex-column">
          <i name="node-sprayer" class="bi bi-broadcast-pin text-center fs-5"></i>
          <i name="node-sprinkler" class="bi bi-water text-center fs-5"></i>
        </li>
      </ul>
    </div>
  </div>
</template>
{% endblock %}

{% block script %}
<script src="{{url_for("static", filename="/js/services.js")}}"></script>
<script>
  $(document).ready(function() {
    class CardNode {
      card;

      constructor(id) {
        let card = $("#template-node").contents().clone();
        card.attr("id", id);

        let card_node_id = card.find("[name='node-id']");
        card_node_id.text(id);
        card_node_id.attr("href", "/node/" + id);
        
        card.find("[name='node-img']")

        $("#nodes").append(card);

        this.card = card;
        this.id = id;
      }

      reload() {
        refreshImage(
          this.card.find("[name='node-img']"),
          S3_ENDPOINT + `${this.id}.bmp`
        )
      }

      set temperature(value) {
        this.card.find("[name='node-temperature']").text(value);
      }

      set moisture(value) {
        this.card.find("[name='node-moisture']").text(value);
      }

      set sprayer(action) {
        if (action == "P1") {
          this.card.find("[name='node-sprayer']").addClass("text-success");
        } else {
          this.card.find("[name='node-sprayer']").removeClass("text-success");
        }
      }

      set sprinkler(action) {
        console.log(action);
        if (action == "W1") {
          this.card.find("[name='node-sprinkler']").addClass("text-success");
        } else {
          this.card.find("[name='node-sprinkler']").removeClass("text-success");
        }
      }
    }

    const cards = {};
    const service = new ServiceNode();

    setIntervalExec(function() {
      service.getNodesAsync(function(nodes) {
        $.each(nodes, function(index, node) {
          let card = (node["id"] in cards) ? cards[node["id"]] : new CardNode(node["id"]);
          cards[node["id"]] = card;

          card.temperature = node["sensors"]["temperature"];
          card.moisture = node["sensors"]["moisture"];

          card.sprayer = node["actions"]["sprayer"];
          card.sprinkler = node["actions"]["sprinkler"];

          card.reload();
        });
      });
    }, 5000);
  });
</script>
{% endblock %}